name: custodia_provider
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+10
  overlay_support: ^1.2.1
  photo_view: ^0.13.0
  flutter_local_notifications: ^9.4.0
  step_progress_indicator: ^1.0.2
  table_calendar: ^3.0.6
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/ProximaNova-Extrabold.ttf
          weight: 800
        - asset: fonts/ProximaNova-Bold.ttf
          weight: 700
        - asset: fonts/ProximaNova-Semibold.ttf
          weight: 600
        - asset: fonts/ProximaNova-Regular.ttf
          weight: 400
        - asset: fonts/ProximaNova-Light.ttf
          weight: 300
        - asset: fonts/ProximaNova-Thin.ttf
          weight: 100

    - family: Circular Std
      fonts:
        - asset: fonts/Circular-Std-Bold.ttf
          weight: 700
        - asset: fonts/Circular-Std-Medium.ttf
          weight: 500
        - asset: fonts/Circular-Std-Regular.ttf
          weight: 400
        - asset: fonts/Circular-Std-Light.ttf
          weight: 300
