name: custodia_provider
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  hooks_riverpod: ^1.0.4
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+10
  overlay_support: ^2.1.0
  flutter_local_notifications: ^9.4.0
  step_progress_indicator: ^1.0.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.3
  shared_preferences: ^2.0.17
  logger: ^1.1.0
  intl: ^0.17.0
  timeago: ^3.2.0
  firebase_messaging: ^14.6.4
  socket_io_client: ^2.0.2
  flutter_linkify: ^5.0.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env

  fonts:
    - family: Circular Std
      fonts:
        - asset: fonts/Circular-Std-Bold.ttf
          weight: 700
        - asset: fonts/Circular-Std-Medium.ttf
          weight: 500
        - asset: fonts/Circular-Std-Regular.ttf
          weight: 400
        - asset: fonts/Circular-Std-Light.ttf
          weight: 300
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
